#!/usr/bin/env bash

# 配置 crontab 以自动更新并同步 IP 列表

crontab <(
	crontab -l 2> /dev/null
	# 每小时在半点定时执行 (00:30, 01:30, 02:30, ...)
	cat <<-EOF
		30 * * * * "$(dirname "$(realpath "$0")")/deploy"
	EOF
)

crontab -l
