#!/usr/bin/env bash

# 配置 crontab 以自动更新并同步 IP 列表

crontab <(
	crontab -l 2> /dev/null
	# 每隔 4 小时在半点定时执行 (00:30, 04:30, 08:30, ...)
	cat <<-EOF
		30 0-23/4 * * * "$(dirname "$(realpath "$0")")/deploy"
	EOF
)

crontab -l
